name = "staticclock-download-tracker"
main = "src/index.js"
compatibility_date = "2026-07-01"
workers_dev = true
account_id = "ac575a9b822bea2bed97d0ab73aed238"

[[kv_namespaces]]
binding = "DOWNLOADS"
id = "3846ce9f571043afbe67e5fff90a0181"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/", "/download", "/download/*", "/stats", "/event", "/go", "/count"]
